name: CI

on:
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Descargar el código fuente del repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configuración de Node.js y caché de dependencias
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Instalación de dependencias del proyecto
      - name: Instalar dependencias
        run: npm ci --legacy-peer-deps


      # Configuración de SHAs para Nx
      - name: Configurar SHAs para Nx
        uses: nrwl/nx-set-shas@v4

      # Analizar las tareas afectadas
      - name: Analizar tareas afectadas
        run: npx nx affected:graph --head=HEAD --base=main

      # Ejecución de Nx Cloud (habilitar agentes distribuidos si es necesario)
      - name: Iniciar Nx Cloud
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Ejecutar las tareas afectadas (lint, build, test, e2e)
      - name: Ejecutar tareas afectadas
        run: npx nx affected -t lint build
