name: CI

on:
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Descargar el código fuente del repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configuración de Node.js y caché de dependencias
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Instalación de dependencias del proyecto
      - run: npm ci --legacy-peer-deps

      # Instalación de Cypress si se usa en el proyecto
      - run: npx cypress install

      # Configuración de SHAs para Nx
      - uses: nrwl/nx-set-shas@v4

      # Ejecución de Nx Cloud (descomenta para habilitar distribución)
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Ejecutar las tareas afectadas (lint, test, build, e2e)
      #- run: npx nx affected -t lint test build e2e
      - run: npx nx affected -t lint build
